### ISSUE TITLE
Missing Research Catalogue Page

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#11]
**Describe the bug**
Trying to view the details of a research catalogue returns an error page

Role: Faculty

**To Reproduce**
1. Go to '/researches/catalogue'.
2. In the DataTable, under 'Action' column, Click on 'View Research'
3. Be redirected to /researches/catalogue/[index]. Error 500

**Expected behavior**
See the page containing the research catalogue details, similar to how research/publications/[index] works

**Screenshots**
![Frame 1](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/1e1590f1-6170-476f-b996-dfb71977cfa5)

**Comment by ceciiiron** [comment]
Fixed research catalogue page for a quick preview of its contents.

https://github.com/ceciiiron/BUCS-RMDS/commit/52a31b308f16e691222f83674daf50459ec03103
