### ISSUE TITLE
Order or roles

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#12]
**Is your feature request related to a problem? Please describe.**
The order of roles should be in chronological order.
**Describe the solution you'd like**
Make the order from Superadmin  to Student 

**Screenshot**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/2110a95d-8e3f-4a6e-ac35-1a947d0ad4ea)

**Comment by ceciiiron** [comment]
The order is correct because you are sorting it in desc order
