### ISSUE TITLE
Super Admin- Student Researches -Undergraduate List display error

### ISSUE THREAD

**Issue by Aizzy10** [ceciiiron/BUCS-RDMS-Issues#17]
**Describe the bug**
When you go to student researches and click on undergraduate, there a prompt that "DataTables warning: table id=main-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7" The data are not displayed on the List of undergraduate student researches.

**To Reproduce**
1. Go to Student Researches
2. Click on Undergraduate
4. See error Prompt warning display

**Expected behavior**
When the "Undergraduate" option is selected, it will show a collection of research projects conducted by undergraduate students.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/130663150/270e9608-7f09-4540-8f6a-a9ffbed7ab0f)

**Comment by ceciiiron** [comment]
Database related issue (Fixed case sensitive table names)

Fixed https://github.com/ceciiiron/BUCS-RMDS/commit/bc5e2478ea35388325ec6f37664e840c38b12ff2
Duplicate #8
