### ISSUE TITLE
Super Admin - Student Researches - Graduate School error

### ISSUE THREAD

**Issue by Aizzy10** [ceciiiron/BUCS-RDMS-Issues#18]
**Describe the bug**
When you go to student researches and click on Graduate school, Error display 404 Sorry! Cannot seem to find the page you were looking for. The data are not displayed on the List of graduate school student researches.

**To Reproduce**
1. Go to Student Researches
2. Click on Graduate school
4. See error Prompt warning display "404
Sorry! Cannot seem to find the page you were looking for."

**Expected behavior**
When the "graduate school" option is selected, it will show a collection of research projects conducted by graduate school.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/130663150/a575e1fc-e8bc-438f-a425-4b9717b04700)

**Comment by ceciiiron** [comment]
Graduate school studies is now merged with undergraduate researches
