### ISSUE TITLE
Superadmin cannot log in when signed in to other devices

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#19]
**Describe the bug**
SuperAdmin cannot log in when signed in on other devices.

**To Reproduce**
1. Go to 'Log In'
2.  See error

**Expected behavior**
Log in to the Homepage of the SuperAdmin.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/3d1404a1-b5c3-401c-a214-22a8714c2bc6)

**Additional context**

**Comment by ceciiiron** [comment]
What browser and device? And with what browser and device can a superadmin login?

**Comment by M-st8k** [comment]
Cannot log in on laptop using chrome browser, but can also log in on laptop using chrome browser.

**Comment by balanarenmar** [comment]
I cannot reproduce.
