### ISSUE TITLE
Award title order

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#20]
**Is your feature request related to a problem? Please describe.**
The order of the awards should be from the highest to the least.

**Describe the solution you'd like**
Make the order the usual expected of awards, letter it is from the first to last or vice versa.

![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/d8704f84-3c53-4270-8dbb-ec7e3508426b)

**Comment by OtokseDom** [comment]
Added hierarchy column to determine award order
