### ISSUE TITLE
Thematic area duplicate

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#21]
**Describe the bug**
Adds a Thematic area even if it already existed in the list.

**To Reproduce**
1. Go to '/settings/researches/thematic_areas'
2. Click on 'add thematic areas'
3. Add thematic area

**Expected behavior**
Will display a pop-up saying it already exists.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/02ec582e-0895-4a8c-8333-020ffb79bd9e)

**Comment by ceciiiron** [comment]
Fixed https://github.com/ceciiiron/BUCS-RMDS/commit/bc5e2478ea35388325ec6f37664e840c38b12ff2

Added unique validation to thematic areas
