### ISSUE TITLE
Login email input darkens on autocomplete

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#22]
**Describe the bug**
While logging in, manually typing out the email is alright. Picking an email using autocomplete changes the input's background color to #3D3D3D.

**To Reproduce**
1. Go to '/login'
2. Click on 'Email'
3. Select any suggested email to autocomplete

**Expected behavior**
Autocomplete does not change the email input's background color.

**Screenshots**
![Frame 1](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/a3dbbe92-c74a-468d-b7c6-05329eba22e4)

**Comment by ceciiiron** [comment]
Fixed https://github.com/ceciiiron/BUCS-RMDS/commit/bc5e2478ea35388325ec6f37664e840c38b12ff2

Override `-webkit-autofill` for form fields in light mode
