### ISSUE TITLE
No Department Applicable when adding a new User Account

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#23]
**Describe the bug**
When attempting to add a new user account, under the University Assignation, there are no options for the Department on all College options

**To Reproduce**
1. Go to '/users/add'
3. Scroll down to 'University Assignation'
4. Select any College.
5. Click on 'Department'
5. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/cd73bb41-3ede-4f76-bb75-e2bd371efe21)

**Additional context**
Proposed solution using javascript 
```javascript
        $("#college_id").change(function() {
            var val = $(this).val();
            if (val == "College of Science") {
                $("#college_department_id").html("<option value='CSIT'>CSIT</option> <option value='Physics Department'>Physics Department</option> <option value='Biology Department'>Biology Department</option>");
            } else if (val == "College of Nursing") {
                $("#college_department_id").html("<option value='A'>A</option> <option value='B'>B</option>");
            } else if (val == "College of Medicine") {
                $("#college_department_id").html("<option value='A'>A</option>");
        });
```

**Comment by ceciiiron** [comment]
Database related issue (Renamed CollegeDepartments to Departments)
Fixed https://github.com/ceciiiron/BUCS-RMDS/commit/bc5e2478ea35388325ec6f37664e840c38b12ff2
Duplicate #2 

Thank you!
