### ISSUE TITLE
No Action for managing User Accounts

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#24]
**Describe the bug**
There is no way to update, or drop user accounts.

**To Reproduce**
as a SUPERADMIN...
1. Go to '/users'
2. Click on '....' under the 'Action' column
3. Click on the button.

**Expected behavior**
dropdown-toggle button should show the list of valid actions such as 'remove', 'update' 'set as inactive' or whatever was implemented.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/1fe49eb0-fd69-4d2b-964f-ec12c479a3ca)

**Comment by ceciiiron** [comment]
Updated view user account

https://github.com/ceciiiron/BUCS-RMDS/commit/ac2e01cf30d47c2bb1f01c79d76e5275408b0557
