### ISSUE TITLE
(Home > Account) Home Button not redirecting

### ISSUE THREAD

**Issue by leanzky** [ceciiiron/BUCS-RDMS-Issues#25]
**Describe the bug**
The functionality of the "Home" button, while viewing the Accounts Tab (Home > Account), which allows users to navigate back to the homepage, does not redirect to the desired location.

**To Reproduce**
1. Go to 'Account'
2. Click on 'Home in (Home > Account) Button'

**Expected behavior**
It should be expected that the button should direct back to the Home Tab

**Screenshots**
![1st](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137733900/bfae6364-264f-40c2-b8db-cc052e8277a5)
![2nd](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137733900/f45e9684-9fbb-4d13-9627-7e4624bdf91b)

**Comment by OtokseDom** [comment]
Fixed Home breadcrumb link
