### ISSUE TITLE
Large button obstructing view in reports tab

### ISSUE THREAD

**Issue by leanzky** [ceciiiron/BUCS-RDMS-Issues#28]
**Describe the bug**
The buttons in /reports while viewing the data obstructs the field of view of the user when clicked or hover.

**To Reproduce**
1. Go to '/reports'
2. Click any of the buttons (College MFO, Externally Funded Resources or BU Funded Resources)
3. Click the next button

**Expected behavior**
The button should not hinder the users viewing experience when clicking next.

**Screenshots**
![Screenshot 2023-07-14 114820](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137733900/8f13424a-a883-48cd-926b-e57ab612dd32)

**Additional context**
Make the large square button

**Comment by OtokseDom** [comment]
Reduced size of button.
