### ISSUE TITLE
Homepage(Researchers)

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#3]
**Describe the bug**
(student)
-the 'Researchers from the Homepage is unresponsive when the user clicks it, unlike the other buttons of the page.

**To Reproduce**
1. Go to 'home'
2. Click on 'Researchers'

**Expected behavior**
-proceed to the page where researchers are displayed.

**Screenshots**
![Screenshot (66)](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/f31d352e-ca98-4ebf-908f-eccfcaf67983)

**Additional context**

**Comment by ceciiiron** [comment]
Added link to user accounts

https://github.com/ceciiiron/BUCS-RMDS/commit/ddfdc11102a210e47353ded1cbc0ed6e9ca939ab
