### ISSUE TITLE
Undergraduate research inputted not reflecting in the DataTable

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#30]
**Describe the bug**
Added a new undergraduate research but there is still nothing displayed in the DataTables for Undergraduate Student Researches

**To Reproduce**
1. Go to '/researches/undergraduates'

**Expected behavior**
Display the inputted researches in the DataTables.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/0fd73896-e5ab-4d39-8dd6-58d2c3de1c75)
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/b0154967-1420-4869-af40-ba0a57f5b0e4)

**Comment by ceciiiron** [comment]
Fixed https://github.com/ceciiiron/BUCS-RMDS/commit/bc5e2478ea35388325ec6f37664e840c38b12ff2

Duplicate #8
