### ISSUE TITLE
Report not generating

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#32]
**Describe the bug**
the report is not generating to a xlsx file.

**To Reproduce**
1. Go to '/reports'
2. Click on 'Generate Report(xlsx)'

**Expected behavior**
Print or generate the file in xlsx format.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/902723c7-c832-4cb3-baeb-f08f870988ce)

**Comment by OtokseDom** [comment]
Added missing report templates in code files.
