### ISSUE TITLE
1000 Character Limit in Student Researches' Abstract

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#34]
**Describe the bug**
After inputting the abstract of the student researches, the full text was cut off at 984 characters resulting in incomplete data.

**To Reproduce**
1. Go to '/researches/undergraduates/add'
2. Add necessary data.
3. Scroll down to 'Abstract'
4. Input contents of 'Abstract' with more than 1,000 characters
5. View the newly added research
6. See Error.

**Expected behavior**
The abstract should have a higher character limit to accommodate longer texts.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/0b283980-46dd-4ee6-9c02-ef908b580a6e)

**Comment by balanarenmar** [comment]
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/3dc6554e-4373-49cb-8c14-069140ed7aad)
This abstract has 1584 characters.

Upon submitting: 
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/f3c03e60-396c-4bf6-8242-641229a153f2)
Only 1000 characters remained

**Comment by ceciiiron** [comment]
Increased abstract character limit to 3000
