### ISSUE TITLE
User Accounts Get Stuck Fetching Data

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#35]
**Describe the bug**
A recurring error when viewing User accounts: table fails to retrieve data. Refreshing the cache is a temporary solution but persists upon restarting of computer.

**To Reproduce**
1. Go to '/users'
2. See error

**Expected behavior**
The user Accounts displayed correctly.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/fbf2bb5e-a632-48cf-bfc2-54c719898422)

**Additional context**
Clearing cache then logging in again and refreshing the page solves the issue, but returns in following sessions.

**Comment by ceciiiron** [comment]
Does the error happen to other datatables?

**Comment by Frenchiy** [comment]
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/127579871/58e83394-c3c9-4e5c-ade1-3ac8b7900526)

Faculty Account
-> Faculty Research

**Comment by Frenchiy** [comment]
Faculty Account
-> Presentations

![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/127579871/ced55f49-0dc1-4fc1-b5aa-c9eecccfab05)

**Comment by balanarenmar** [comment]
Can no longer reproduce in User Accounts table, assume to be fixed.
But happens  in faculty researches

> Faculty Account
> -> Faculty Research

**Comment by Frenchiy** [comment]
I tried opening "faculty researches" page in Microsoft Edge and it worked, but stuck on "fetching data" using Google Chrome.
