### ISSUE TITLE
Wrong Toast Message when Updating Undergraduate Research Entries

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#36]
**Describe the bug**
Updating undergraduate research gives the wrong toast message. 

**To Reproduce**
1. Go to '/researches/undergraduates'
2. Click on 'View Research' on any entry
3. Click on 'Update Research Details' In the Research Information Page
4. Create any edits
5. See Error.

**Expected behavior**
Toast message should be about the updated entries, not adding new one.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/84223bc8-b64f-418e-90a8-12ee588c80fc)
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/0f3cb9c3-3b9b-40ea-a60e-93668ada25ca)

**Comment by ceciiiron** [comment]
Fixed toast message

https://github.com/ceciiiron/BUCS-RMDS/commit/ddfdc11102a210e47353ded1cbc0ed6e9ca939ab
