### ISSUE TITLE
Typographical Error: in Undergraduate Keywords

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#37]
**Describe the bug**
"separate" appears as "separte"

**To Reproduce**
1. Go to '/researches/undergraduates'
2. Click on 'Add new research'
3. Scroll down to 'Keywords'
4. See Typo

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/a1158cc5-75df-4928-b93f-6445576b2bc5)

**Note**
Same typo appears when editing research details
/researches/undergraduates/{index}/update

**Comment by ceciiiron** [comment]
Fixed typographical error

https://github.com/ceciiiron/BUCS-RMDS/commit/ddfdc11102a210e47353ded1cbc0ed6e9ca939ab
