### ISSUE TITLE
Broken search in Student Research DataTables

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#38]
**Describe the bug**
Search input does nothing when trying to search.

**To Reproduce**
1. Go to '/undergraduates'
2. Click on 'search'
3. Type in anything

**Expected behavior**
Search queries would only retrieve matching results. When searching for invalid keywords with no matches, no results should show.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/370793c4-5179-485b-8386-5bcfccb2566e)
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/ac004dc1-6330-4edc-b73d-f89b349546c2)

**Comment by ceciiiron** [comment]
Fixed search. Student research is now searchable by title or keywords

https://github.com/ceciiiron/BUCS-RMDS/commit/52a31b308f16e691222f83674daf50459ec03103
