### ISSUE TITLE
DataTable not correctly sorting by date 

### ISSUE THREAD

**Issue by balanarenmar** [ceciiiron/BUCS-RDMS-Issues#5]
**Describe the bug**
The sort by date function in the DataTable is not working properly. Order seemingly by random

**To Reproduce**
1. Go to '/researches/catalogue'
2. Click on 'Duration > Start' or 'Duration > End' to sort by starting or completion date respectively
3. Scroll down to compare order of entries

**Expected behavior**
When sorting by date and the sort-icon arrow points up, the earliest / oldest entry should show first in the list.
Consequently, when the sort-icon points down, the entry with the most recent  / latest date should show first in the list.

**Screenshots**
![Frame 1](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/a5870b2e-cfcb-4345-a18c-7f173b5155bb)

**Comment by balanarenmar** [comment]
![Screenshot 2023-07-13 114754](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/95604336/a58dafd9-6ed4-4645-9379-eadb52ba9bc4)
Note: the date format in the 'date presented' column inside researches/presentations, is sorted properly

**Comment by ceciiiron** [comment]
Dates are now formatted on the client side to sort the dates on the server side properly.

https://github.com/ceciiiron/BUCS-RMDS/commit/ddfdc11102a210e47353ded1cbc0ed6e9ca939ab
