### ISSUE TITLE
'Actions' and 'Documents' button (r-student)

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#6]
**Describe the bug**
When the browser is in inspect mode, there are button 'Actions' and 'Documents' buttons but when it is in normal view, there isn't.

**To Reproduce**
1. Go to 'researches/publications'
2. Click on 'additional publication'
3. See error

**Expected behavior**
Display the 'Actions' and 'Documents' in the normal view browser.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/44b2e63e-2143-4276-a60b-83d01fb524d1)
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/b9b39609-5902-4639-9d8a-ab6f8e2ecaf9)

**Additional context**

**Comment by M-st8k** [comment]
When you clicked the Publication Manuscript from the Documents of Publications when you are in the Insect Mode, it opens in another tab, might as well open it in the current tab to avoid confusion.

**Comment by ceciiiron** [comment]
Removed  'Actions' and 'Documents'  from mobile view
