### ISSUE TITLE
Student Researches Error

### ISSUE THREAD

**Issue by Aizzy10** [ceciiiron/BUCS-RDMS-Issues#7]
**Describe the bug**
When you go to Home and click on Students Researches  404 not found will display.

**To Reproduce**
1. Go to Home
2. Click on Students Researches
4. See error 404 not found

**Expected behavior**
Once I click the Student Researches it should display the expected output of the List of the Researches conducted by the students.

**Screenshots**
![Research](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/130663150/a6f66929-98b1-4452-9c13-fafbc10ab53b)

**Additional context**

**Comment by ceciiiron** [comment]
Fixed. Edited anchor tag

https://github.com/ceciiiron/BUCS-RMDS/commit/4c09a3879924080b47191ed76f5d7fdcf27c1fba
