### ISSUE TITLE
DataTable Warning

### ISSUE THREAD

**Issue by M-st8k** [ceciiiron/BUCS-RDMS-Issues#8]
**Describe the bug**
There is a DataTable warning when you clicked the Undergraduate from the student researches dropdown and the options of it also have the same errors.

**To Reproduce**
1. Go to 'Student Researches'
2. Click on 'Undergraduate'
3. See error

**Expected behavior**
No error will pop up in the screen.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/137443345/16173a53-d44c-4907-81dc-4eb69bbc541f)

**Comment by ceciiiron** [comment]
Fixed https://github.com/ceciiiron/BUCS-RMDS/commit/bc5e2478ea35388325ec6f37664e840c38b12ff2

Database related issue (Fixed case sensitive table names)
