### ISSUE TITLE
Super Admin - Adding accounts

### ISSUE THREAD

**Issue by Aizzy10** [ceciiiron/BUCS-RDMS-Issues#9]
**Describe the bug**
When you add accounts under University assignment, the department section does not respond. It only displays a "not applicable" message.

**To Reproduce**
1. Go to Accounts
2. Click on Add User
3. Scroll down to University Assignation - Department
4. See error Department is not Responsive.

**Expected behavior**
When you click the Dropdown button of the Department it should display the option of different departments of the specific College/Campus.

**Screenshots**
![image](https://github.com/ceciiiron/BUCS-RDMS-Issues/assets/130663150/e788cb96-3176-4929-b6b5-5f80efddd587)

**Additional context**

**Comment by ceciiiron** [comment]
Database Issue (Renamed CollegeDepartments to Departments)

Fixed https://github.com/ceciiiron/BUCS-RMDS/commit/bc5e2478ea35388325ec6f37664e840c38b12ff2
Duplicate #2
